### ISSUE TITLE
extension working within Typo3 8.7 

### ISSUE THREAD

**Issue by frikas** [docmcfly/loginViaEmail#1]
I have integrated the code into my extension running under Typo3 V8.7.32. The login using E-mail works fine. 
Thanks to clemens for the code!

Still some minor comments:
- The function "getLoginFormData" is called three times. Is this OK or is this a site effect using V8.7.32 ?

Best regards
Fritz

**Comment by docmcfly** [comment]
I am simply courageous and add 8.7.32 - 8.7.99 to the extension. 

Thanks to Fritz for the 8.7 test. 

Greetings Clemens

**Comment by docmcfly** [comment]
Version 0.9.11 is now also "released" for 8.7.11-8.7.32 

The new version is available for download in the repository. 

Greetings Clemens

**Comment by docmcfly** [comment]
Version 9.12 is better. The repository does not accept the notation: "8.7.32-8.7.99,9.5.0-9.5.99". 
I must change it to: "8.7.32-9.5.99" :(
