### ISSUE TITLE
v2.0 tag missing

### ISSUE THREAD

**Issue by nhovratov** [docmcfly/loginViaEmail#11]
Hey, did you delete the v2.0 tag by any chance?
I have this in my composer.lock and now composer install is failing.

```
            "name": "cylancer/loginviaemail",
            "version": "v2.0",
            "source": {
                "type": "git",
                "url": "https://github.com/docmcfly/loginViaEmail.git",
                "reference": "5fd371b6c3472731eff2a4b69b444d05e77bf2c9"
            },
```

**Comment by docmcfly** [comment]
Sorry. I didn't think someone would actually include my extension in their composer. :)  

I have been pointed out by https://packagist.org again and again that my version information is not in order. 
So I cleaned everything up a bit.  

Are you still using Typo3 10 or older?

**Comment by nhovratov** [comment]
Thanks for the fast reply. Yes, in this case this is a v10 instance which requires version 2 of your extension.

**Comment by docmcfly** [comment]
You are lucky. I still had the "v2.0" tag locally and was able to restore it.
Can you please try if everything works as you are used to. 

Thanks for your feedback in advance...

**Comment by nhovratov** [comment]
Hey, thanks for restoring the v2 tag! Looks like packagist does not pick up your changes automatically. "Auto-Update" is not active. Can you have a look in packagist?

**Comment by docmcfly** [comment]
Unfortunately, no v2.0 version appears under Packagist. Even if I click on Update at Packagist quite often.

You can try it again... but I don't hold out much hope. Maybe Packagist is not designed for this...

**Comment by nhovratov** [comment]
Ah, maybe you need to create a v2 branch.

**Comment by docmcfly** [comment]
Please try it again....

**Comment by nhovratov** [comment]
Now it complains, that typo3/cms-core:^11.5 is required for v2 :)

**Comment by docmcfly** [comment]
If this doesn't work now, I'm starting to run out of ideas....

**Comment by nhovratov** [comment]
I can use now `"cylancer/loginviaemail": "^v2.0-dev"` that works for me, thank you very much!!

**Comment by docmcfly** [comment]
😊
