### ISSUE TITLE
Class 'Cylancer\Loginviaemail\XClass\CyFrontendUserAuthentication' not found

### ISSUE THREAD

**Issue by aghausulhag** [docmcfly/loginViaEmail#3]
Hi, I get an error "Class 'Cylancer\Loginviaemail\XClass\CyFrontendUserAuthentication' not found" after installation.
TYPO3  10.4.4 LTS
Best regards

**Comment by docmcfly** [comment]
Hello, 

Thanks for your hint. I have updated my development system from 10.4.3 to 10.4.4. After the deleting of the caches and the restarting of the webserver (apache2  + fastcgi + OPcache) the extension is work fine. 

I can not reproduce your issue. Is the class in the right place? 
`/typo3conf/ext/loginviaemail/Classes/XClass/CyFrontendUserAuthentication.php` 

Best regards
Clemens

**Comment by aghausulhag** [comment]
I found the error. Because I'm using a TYPO3 composer installation, the error was in the composer file. 
Many thanks for your help! 
Best regards
